-- POSTKU database v1 (Supabase/PostgreSQL)
-- Run this in Supabase SQL Editor after creating a project.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(14,2) not null default 0,
  category text not null default 'Lainnya',
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  buyer_name text not null default 'Umum',
  table_no text,
  status text not null default 'pending' check (status in ('pending','paid','cancelled')),
  payment_method text not null default '-',
  cash_received numeric(14,2) not null default 0,
  change_amount numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  cashier_username text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id bigint,
  product_name text not null,
  unit_price numeric(14,2) not null default 0,
  quantity integer not null default 1 check (quantity > 0),
  subtotal numeric(14,2) not null default 0
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

-- For the first prototype, keep RLS disabled until the Auth policies are added.
-- The production version should enable RLS and use Supabase Auth before exposing writes.
